### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by yurivangeffen** [AdColony/AdColony-Unity-SDK-3#34]
I just implemented this SDK in a game that already contained an old version. It compiles fine and seems to work on iOS, but Android gives me the following exception when calling `AdColony.Ads.RequestInterstitialAd(zone.Identifier, null)`:

`12-22 13:37:08.657 15302 15329 E Unity   : java.lang.ClassCastException: org.json.JSONObject$1 cannot be cast to java.lang.String
12-22 13:37:08.657 15302 15329 E Unity   : 	at com.adcolony.unityplugin.UnityADCAds.requestInterstitialAd(UnityADCAds.java:232)
12-22 13:37:08.657 15302 15329 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
12-22 13:37:08.657 15302 15329 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
12-22 13:37:08.657 15302 15329 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
12-22 13:37:08.657 15302 15329 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-22 13:37:08.657 15302 15329 E Unity   : 	at android.os.Looper.loop(Looper.java:158)
12-22 13:37:08.657 15302 15329 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
12-22 13:37:08.657 15302 15329 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
12-22 13:37:08.657 15302 15329 E Unity   :   at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0`

Confirmed that removing the call removes the exception.

**Comment by yurivangeffen** [comment]
Seems that zone.Identifier == null. Will check why this is the case (it comes from ADC) and possibly file a new issue.
